services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: disagro-database
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./backend/src/database:/scripts
      - disagro_sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  disagro_sqlserver_data:
